lots of changes

diff --git a/makefile.template b/makefile.template
--- a/makefile.template
+++ b/makefile.template
@@ -7,7 +7,7 @@
 
 MAKEFLAGS += --warn-undefined-variables
 SHELL := /bin/bash
-.SHELLFLAGS := -O extglob -eo pipefail -c
+.SHELLFLAGS := -O extglob -O globstar -eo pipefail -c
 .DEFAULT_GOAL := help
 .SUFFIXES:
 
@@ -28,7 +28,7 @@ ifndef SUPPORTED_PYTHON_VERSIONS
 endif
 
 PKG_NAME := $(PACKAGE_NAME)
-SRC_PATH = src/
+MODULE_SRC_PATH = src/$(PKG_NAME)/
 
 # TODO (mb 2018-09-23): Support for bash on windows
 # 	perhaps we need to install conda using this
@@ -36,7 +36,7 @@ SRC_PATH = src/
 PLATFORM = $(shell uname -s)
 
 # miniconda is shared between projects
-CONDA_ROOT := $(HOME)/miniconda3
+CONDA_ROOT := $(shell if [[ -d /opt/conda ]]; then echo "/opt/conda"; else echo "$$HOME/miniconda3"; fi;)
 CONDA_BIN := $(CONDA_ROOT)/bin/conda
 
 ENV_PREFIX := $(CONDA_ROOT)/envs
@@ -51,20 +51,9 @@ CONDA_ENV_PATHS := \
 	$(subst py,${ENV_PREFIX}/$(PKG_NAME)_py,$(subst .,,$(subst =,,$(subst thon,,$(SUPPORTED_PYTHON_VERSIONS)))))
 
 
+# default version for development
 DEV_ENV := $(ENV_PREFIX)/$(DEV_ENV_NAME)
 DEV_ENV_PY := $(DEV_ENV)/bin/python
-
-# TODO (mb 2018-09-27): download
-#	scripts/setup_conda_envs.sh
-
-PYENV37 := $(CONDA_ROOT)/envs/$(PKG_NAME)_py37
-PYENV36 := $(CONDA_ROOT)/envs/$(PKG_NAME)_py36
-PYTHON37 := $(PYENV37)/bin/python
-PYTHON36 := $(PYENV36)/bin/python
-
-# default version for development
-PYENV = $(PYENV36)
-PYTHON = $(PYTHON36)
 
 
 build/envs.txt: requirements/conda.txt
@@ -146,7 +135,7 @@ build/deps.txt: build/envs.txt requirements/*.txt
 ## This help message
 .PHONY: help
 help:
-	@printf "Available make targets for \033[97m$(PKG_NAME)\033[0m:\n"
+	@printf "Available make targets for \033[97m$(PKG_NAME)\033[0m:\n";
 
 	@grep -hzoP '\n(\n##.*?)+\n(\.PHONY: [a-zA-Z_-]+)?' $(MAKEFILE_LIST) \
 		| sed -zr "s/\n\n##([^\n]*)\n/\n-INIT-\1-NL-/g" \
@@ -155,9 +144,9 @@ help:
 		| awk -F"-FS-" '{ printf "    \033[36m%-12s\033[0m %s\n", $$2, $$1 }' \
 		| sed -z "s/-INIT-//g" \
 		| sed -z "s/-NL-[^\n]/\n                  /g" \
-		| sed -z "s/-NL-//g"
+		| sed -z "s/-NL-//g";
 
-	@echo ""
+	@echo "";
 
 	@if [[ ! -f $(DEV_ENV_PY) ]]; then \
 	echo "Missing python interpreter at $(DEV_ENV_PY) !"; \
@@ -184,13 +173,12 @@ help:
 ## Delete conda envs and cache 💩
 .PHONY: clean
 clean:
-	@if test -f $(PYTHON37); then \
-	$(CONDA_BIN) env remove --name $(PKG_NAME)_py37 --yes; \
-	fi
-
-	@if test -f $(PYTHON36); then \
-	$(CONDA_BIN) env remove --name $(PKG_NAME)_py36 --yes; \
-	fi
+	@for env_name in $(CONDA_ENV_NAMES); do \
+		env_py="${ENV_PREFIX}/$${env_name}/bin/python"; \
+		if [[ -f $${env_py} ]]; then \
+			$(CONDA_BIN) env remove --name $${env_name} --yes; \
+		fi; \
+	done
 
 	rm -f build/envs.txt
 	rm -f build/deps.txt
@@ -203,6 +191,20 @@ clean:
 	@printf "\n setup/update completed  ✨ 🍰 ✨ \n\n"
 
 
+## Force update of dependencies
+##   (this removes makefile markers)
+.PHONY: force
+force:
+	rm -f build/envs.txt
+	rm -f build/deps.txt
+	rm -rf vendor/
+	rm -rf .mypy_cache/
+	rm -rf .pytest_cache/
+	rm -rf __pycache__/
+	rm -rf src/__pycache__/
+	rm -rf vendor/__pycache__/
+
+
 ## Setup python virtual environments
 .PHONY: install
 install: build/deps.txt
@@ -213,11 +215,11 @@ install: build/deps.txt
 update: build/deps.txt
 
 
-## TODO: Install git pre-push hooks
+## Install git pre-push hooks
 .PHONY: git_hooks
 git_hooks:
-	@rm -f ${PWD}/.git/hooks/pre-push
-	ln -s ${PWD}/scripts/pre-push-hook.sh ${PWD}/.git/hooks/pre-push
+	@rm -f "${PWD}/.git/hooks/pre-push"
+	ln -s "${PWD}/scripts/pre-push-hook.sh" "${PWD}/.git/hooks/pre-push"
 
 
 # TODO make target to publish on pypi
@@ -233,39 +235,79 @@ git_hooks:
 .PHONY: fmt
 fmt:
 	@$(DEV_ENV)/bin/sjfmt --py36 --skip-string-normalization --line-length=100 \
-		 $(SRC_PATH)*.py $(SRC_PATH)*/*.py test/*.py
+		 src/ test/
 
 
-# TODO: add linting for .md files using readme_renderer
-
-## Run flake8 linter and mypy type checker
+## Run flake8 linter
 .PHONY: lint
 lint:
 	@printf "flake8 ..\n"
-	@$(DEV_ENV)/bin/flake8 $(SRC_PATH)
+	@$(DEV_ENV)/bin/flake8 src/
 	@printf "\e[1F\e[9C ok\n"
+
+
+## Run mypy type checker
+.PHONY: lint
+lint:
+	@rm -rf ".mypy_cache";
 
 	@printf "mypy ....\n"
-	@MYPYPATH=stubs/:vendor/ $(DEV_ENV_PY) -m mypy $(SRC_PATH)
+	@MYPYPATH=stubs/:vendor/ $(DEV_ENV_PY) -m mypy src/
 	@printf "\e[1F\e[9C ok\n"
 
-	@printf "docs ....\n"
-	@printf "\e[1F\e[9C NA\n"
+
+## Run pylint. Should not break the build yet
+.PHONY: pylint
+pylint:
+	@printf "pylint ..\n";
+	@pylint --jobs=4 --output-format=colorized --score=no \
+		 --disable=C0103,C0301,C0330,C0326,C0330,C0411,R0903,W1619,W1618,W1203 \
+		 --extension-pkg-whitelist=ujson,lxml,PIL,numpy,pandas,sklearn,pyblake2 \
+		 src/
+	@pylint --jobs=4 --output-format=colorized --score=no \
+		 --disable=C0103,C0111,C0301,C0330,C0326,C0330,C0411,R0903,W1619,W1618,W1203 \
+		 --extension-pkg-whitelist=ujson,lxml,PIL,numpy,pandas,sklearn,pyblake2 \
+		 test/
+
+	@printf "\e[1F\e[9C ok\n"
 
 
 ## Run pytest unit and integration tests
 .PHONY: test
 test:
+	@rm -rf ".pytest_cache";
+	@rm -rf "src/__pycache__";
+	@rm -rf "test/__pycache__";
+
 	ENV=dev PYTHONPATH=src/:vendor/:$$PYTHONPATH \
 		$(DEV_ENV_PY) -m pytest -v \
 		--doctest-modules \
 		--cov-report html \
 		--cov-report term \
 		--cov=$(PKG_NAME) \
-		test/ src/
+		test/ src/;
+
+	@rm -rf ".pytest_cache";
+	@rm -rf "src/__pycache__";
+	@rm -rf "test/__pycache__";
 
 
 ## -- Helpers --
+
+
+## Shortcut for make fmt lint pylint test
+.PHONY: check
+check:  fmt lint pylint test
+
+
+## Set environ variables in shell.
+## 	Usage: eval $(make env)
+.PHONY: env
+env:
+	@echo "export ENV=dev;";
+	@echo "export PYTHONPATH=\"src/:vendor/:$$PYTHONPATH\";";
+	@echo "export PATH=\"$(DEV_ENV)/bin/:$$PATH\";";
+	@echo "";
 
 
 ## Drop into an ipython shell with correct env variables set
@@ -278,15 +320,79 @@ ipy:
 ## like `make test`, but with debug parameters
 .PHONY: devtest
 devtest:
+	@rm -rf ".pytest_cache";
+	@rm -rf "src/__pycache__";
+	@rm -rf "test/__pycache__";
+
+
+ifndef FILTER
 	ENV=dev PYTHONPATH=src/:vendor/:$$PYTHONPATH \
 		$(DEV_ENV_PY) -m pytest -v \
 		--doctest-modules \
-		--cov-report term \
-		--cov=$(PKG_NAME) \
+		--no-cov \
 		--verbose \
 		--capture=no \
 		--exitfirst \
-		test/ src/
+		test/ src/;
+else
+	ENV=dev PYTHONPATH=src/:vendor/:$$PYTHONPATH \
+		$(DEV_ENV_PY) -m pytest -v \
+		--doctest-modules \
+		--no-cov \
+		--verbose \
+		--capture=no \
+		--exitfirst \
+		-k $(FILTER) \
+		test/ src/;
+endif
+
+	@rm -rf ".pytest_cache";
+	@rm -rf "src/__pycache__";
+	@rm -rf "test/__pycache__";
+
+
+## -- Build/Deploy --
+
+
+## Generate Documentation
+.PHONY: doc
+doc:
+	echo "Not Implemented"
+
+
+## Create python sdist and bdist_wheel distributions
+.PHONY: build_dist
+build_dist:
+	python setup.py sdist bdist_wheel
+	twine check dist/*
+	echo "to upload to pypi run:\n\tpython setup.py upload"
+
+
+## Build docker images. Must be run when dependencies are added
+##   or updated. The main reasons this can fail are:
+##   1. No ssh key at $(HOME)/.ssh/${PKG_NAME}_gitlab_runner_id_rsa
+##      (which is needed to install packages from private repos
+##      and is copied into a temp container during the build).
+##   2. Your docker daemon is not running or configured to
+##      expose on tcp://localhost:2375
+.PHONY: build_docker
+build_docker:
+	if ! [[ -f $$HOME/.ssh/${PKG_NAME}_gitlab_runner_id_rsa ]]; then \
+		echo "File not found: $$HOME/.ssh/${PKG_NAME}_gitlab_runner_id_rsa"; \
+		exit 1; \
+	fi
+
+	cp $(HOME)/.ssh/${PKG_NAME}_gitlab_runner_id_rsa build/tmp_ssh_key
+
+	DOCKER_HOST=localhost:2375 docker build \
+		--file docker_base.Dockerfile \
+		--tag $(DOCKER_REGISTRY_URL)/base:latest \
+		.
+
+	rm build/tmp_ssh_key
+
+	DOCKER_HOST=localhost:2375 docker push \
+		$(DOCKER_REGISTRY_URL)/base:latest
 
 
 -include makefile.extra.make
